- name: Ensure package directory exists
  file:
    path: "../app/backend/package"
    state: directory

- name: Package app
  shell: |
    cp -r app/ package/
    cp database.db package/
    cp -r venv/lib/python3.10/site-packages/* package/
  args:
    chdir: "../app/backend"

- name: Archive package
  archive:
    path: "../app/backend/package/"
    dest: /tmp/{{ TF_VAR_s3_key }}
    format: zip