- name: Add PPA for Python 3.10
  ansible.builtin.command: "add-apt-repository ppa:deadsnakes/ppa -y"

- name: Update apt after add PPA
  ansible.builtin.command: "apt update"

- name: Install Python 3.10 and venv
  ansible.builtin.command: "apt install python3.10 python3.10-venv -y"
  args:
    chdir: "../app/backend"
    
- name: Create an virtual environnement
  command: python3.10 -m venv venv
  args:
    chdir: "../app/backend"
